### ISSUE TITLE
`JSON` type in GraphQL is not respected and returns null

### ISSUE THREAD

**Issue by jackstine** [k8sgateway/k8sgateway#8182]
### Gloo Edge Version

1.13.x

### Kubernetes Version

None

### Describe the bug

The GraphQL `JSON` type is not respected and returns `null`.  When querying links below the result is `null`.  

```graphql
"""The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf)."""
scalar JSON

type CollectionOrderModel {
  embedded: Embedded3
  links: JSON
}
```

`links` is an openAPI type below (map), this gets represented as a `JSON` type in GraphQL.
```json
"Links": {
    "type": "object",
    "additionalProperties": {
        "$ref": "#/components/schemas/Link"
    }
},
```

### Steps to reproduce the bug

Query data that contains a `JSON` scalar type.

### Expected Behavior

Expect that the scalar type returns a string representation of the JSON data.

**Comment by jackstine** [comment]
Currently, doing investigation and analysis on this issue. I think the following steps need to be completed.
- [ ] have a server that generates the JSON type for openAPI
- [ ] See if the problem resides in Envoy alone, or is a misinterpretation of the GraphQL Schema.

**Comment by saiskee** [comment]
There are two possible solutions to this that I see going forward:
- Implement a natively supported JSON type. This would mean that we support it as just another scalar out of the box. 
  - Pros: Simpler implementation, Other approaches do not offer this out of the box
  - Cons: It is not part of the graphql spec, would not be expected behavior and have to be explicitly documented that we support the JSON scalar natively.
    - **not extensible** this would be a one off sort of fix, since it only supports the JSON Scalar.
- Custom Scalar approach: Allow users to introduce their own scalars and write their own `serialize` and `parseValue` functions for these scalars.
  -  Pros: Known approach ([apollo docs](https://www.apollographql.com/docs/apollo-server/schema/custom-scalars/))
    - GraphQL tools wrote their JSON custom scalar to be used as a library ([source](https://github.com/taion/graphql-type-json)), and is imported by devs into their graphql servers.
    -  We can include the JSON custom scalar "out of the box", while also providing support for custom scalars with serialization and parsing logic provided by users through `jq` filters

I'm of the opinion to do the work for custom scalars since that is something that has been lacking from our graphql offering and there is an existing ticket for it as part of our [Support full graphql spec epic](https://github.com/solo-io/solo-projects/issues/3414)

**Comment by kdorosh** [comment]
agree with sticking to existing standards and tooling as opposed to rolling anything custom

**Comment by jackstine** [comment]
Adding https://github.com/solo-io/solo-projects/issues/4925 as this is the second option mentioned above.
