### ISSUE TITLE
Helm param to use custom Redis secret instead of generating new secret 

### ISSUE THREAD

**Issue by bdecoste** [k8sgateway/k8sgateway#8252]
### Version

None

### Is your feature request related to a problem? Please describe.

I need to be able to use a pre-existing Redis secret for rate-limit and extauth in a Gloo helm install/upgrade without having the Gloo helm install/upgrade creating a new secret 

### Describe the solution you'd like

Add a param to the helm charts to set a custom redis secret name. If set this secret would be used by rate-limit and extauth. No Redis secret would be generated if set. 

### Describe alternatives you've considered

None

**Comment by jackstine** [comment]
Similar to https://github.com/solo-io/solo-projects/issues/4897

How would a default name instead of providing the name.  The mentioned issue will do the following.

If `global.extensions.glooRedis.enableAcl` is set, the secret will be `redis`, and the key for the password will be `redis-password`.  If the `redis.disabled` is set, the secret will not be created, meaning that the client will have to create this.


Although this issue, mentions that the client should be able to provide the name of the secret, I think we can just use the default name.  The mentioned issue https://github.com/solo-io/solo-projects/issues/4897 should solve the problems mentioned in this issue.

**Comment by ashutosh887** [comment]
I would like to work on this @jackstine @bdecoste 
Please assign me this issue
